services:
  whatsapp-bridge:
    build:
      context: ./whatsapp-bridge
      dockerfile: Dockerfile
    container_name: whatsapp-bridge
    ports:
      - "38080:8080"
    volumes:
      - ./whatsapp-data:/app/data
      - ./whatsapp-store:/app/store
    environment:
      - DB_PATH=/app/data/whatsmeow.db
      - UID=1001
      - GID=1001
    restart: unless-stopped

  whatsapp-mcp-server:
    build:
      context: ./whatsapp-mcp-server
      dockerfile: Dockerfile
    container_name: whatsapp-mcp-server
    ports:
      - "9876:8000"
    volumes:
      - ./whatsapp-store:/app/store:ro
    environment:
      - MESSAGES_DB_PATH=/app/store/messages.db
      - UID=1001
      - GID=1001
    restart: unless-stopped
